project:
  type: website
  output-dir: docs
  resources:
    - headshot.jpg
    - MichelleRicart_Resume.pdf

website:
  title: "Michelle Marie Ricart â€” MBA Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: skills.qmd
        text: Skills & Certifications
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: litera
    css: styles.css

